### ISSUE TITLE
How to install non-local network?

### ISSUE THREAD

**Issue by XavierLinNow** [vt-vl-lab/cluster#3]
The installation instruction of Non-Local Neural Network shows "It does not work right now...", could you tell me how to install non-local network

**Comment by Buted** [comment]
@XavierLinNow have you installed the Non-Local Neural Network? I also want to install the model, but failed.

**Comment by Yuliang-Zou** [comment]
Non-Local Neural Network is now supported in PyTorch: https://github.com/facebookresearch/SlowFast

It should be easy to set up the code.
